### ISSUE TITLE
RBAC authentication for CRD resources

### ISSUE THREAD

**Issue by despondency** [jvm-operators/abstract-operator#47]
Problem is now, the Entrypoint creates a new DefaultKubernetesClient(), without taking into account if you use CRD's that are protected by RBAC. Is there a way to configure RBAC's certificates in the KubernetesClient with the current implementation?

Best, 

Mario

**Comment by Jiri-Kremser** [comment]
Could you please  elaborate here a bit? I am not sure what you mean by "RBAC's certificates". the `new DefaultKubernetesClient()` should be 0-configuration mechanism that should create the client possibly from different sources in the following order of priority:

* System properties
* Environment variables
* Kube config file
* Service account token & mounted CA certificate

There is also `DefaultKubernetesClient(Config config)` constructor where a lot of things can be customized in the `config`, are you asking about this feature? Because when reading "CRD's that are protected by RBAC" I can imagine the rules in the yaml file like in [here](https://github.com/radanalyticsio/spark-operator/blob/master/manifest/operator-cm.yaml#L6:L26) ~ "AuthZ" and not certificates. Certificates are often used w/ asymmetric crypto for AuthN rather than AuthZ, but Kubernetes is a huge beast and it's more than possible that I am missing some important feature here :)

**Comment by despondency** [comment]
Hello,

I think we understood each other, i meant that if i generate a certificate for a user and create a ServiceAccount assigning ClusterRole/Roles to this ServiceAccount, I am used to configuring it with the DefaultKubernetesClient(Config config) constructor, but from what you are typing, it seems you can do it with env vars/system vars or with the kubeconfig on the machine.

Thanks Jiri,

Best,

Mario
